[[pages]]
path = "markdown.py"
name = "Readme"
icon = "ğŸ“”"

[[pages]]
name = "Features"
icon = ""
is_section = true

[[pages]]
path = "document_ui.py"
name = "Document UI"
icon = "ğŸ—ƒï¸"

[[pages]]
path = "pages/metrics_ui.py"
name = "Metrics UI"
icon = "ğŸ“Š"

[[pages]]
path = "chat_ui.py"
name = "Chat UI"
icon = "ğŸ—¨ï¸"